config/routes.rb
Utour::Application.routes.draw do

  resources :date_and_prices

  resources :tours do
    get 'legacy', on: :member
    get 'show_docx', on: :member
  end

  resources :bookings do
    get 'account_specific_index', on: :collection
  end

  resources :accounts do
    get 'activate_show', on: :member
    post 'activate', on: :member
  end

  resources :agents

  resources :images, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :visa_infos, only: [:show]

  root 'front30#home'

  match '/signup',  to: 'accounts#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signout', to: 'sessions#destroy', via: 'get'

  match '/legacy/home', to: 'legacies#home', via: 'get'

  match '/legacy/group_tours', to: 'legacies#group_tours', via: 'get'
  match '/legacy/free_tours', to: 'legacies#free_tours', via: 'get'
  match '/legacy/assorted', to: 'legacies#assorted', via: 'get'
  match '/legacy/visa', to: 'legacies#visa', via: 'get'
  match '/legacy/my_booking', to: 'legacies#my_booking', via: 'get'
  match '/legacy/booking_status', to: 'legacies#booking_status', via: 'get'
  match '/legacy/info', to: 'legacies#info', via: 'get'
  match '/legacy/guide', to: 'legacies#guide', via: 'get'

  match '/wechat', to: 'wechats#check', via: 'get'
  match '/wechat', to: 'wechats#message', via: 'post'
  match '/wechat/debug', to: 'wechats#debug', via: 'get'

  match '/tiger', to: 'wechat_webs#tiger', via: 'get'
  match '/lion', to: 'wechat_webs#lion', via: 'get'
  match '/tiger/group_travel', to: 'wechat_webs#group_travel', via: 'get'
  match '/lion/group_travel', to: 'wechat_webs#group_travel', via: 'get'
  match '/lion/visa', to: 'wechat_webs#visa', via: 'get'
  match '/lion/trade', to: 'wechat_webs#trade', via: 'get'
  match '/lion/video', to: 'wechat_webs#video', via: 'get'
  match '/lion/contact', to: 'wechat_webs#contact', via: 'get'
  match '/lion/feedback', to: 'wechat_webs#feedback', via: 'post'
  match '/lion/diy', to: 'wechat_webs#diy', via: 'get'
  match '/lion/sale', to: 'wechat_webs#sale', via: 'get'
  match '/lion/guide', to: 'wechat_webs#guide', via: 'get'
  get '/lion/visa_detail', to: 'wechat_webs#visa_detail'

  get '/landing_page', to: 'front30#landing_page'

  get '/front30/home', to: 'front30#home'
  get '/front30/contact_about', to: 'front30#contact_about'
  get '/front30/about', to: 'front30#about'
  get '/front30/dm', to: 'front30#dm'
  get '/front30/video', to: 'front30#video'
  get '/front30/travel_guide', to: 'front30#travel_guide'
  get '/front30/group', to: 'front30#group'
  get '/front30/free', to: 'front30#free'
  get '/front30/onsale', to: 'front30#onsale'
  get '/front30/quick_booking', to: 'front30#quick_booking'

  

  namespace :admin do |admin|
    
    resources :accounts
    resources :admins
    resources :operators
    resources :sales
    resources :agents

    resources :tours do
      resources :departures do 
        resources :prices
      end
    end
    resources :bookings
    resources :user_groups
    resources :date_and_prices
    resources :shelves

    resources :feature_tag_connections, only: [:new, :create, :destroy, :index]
    resources :feature_tags, only: [:new, :create, :destroy, :index]
    resources :invitation_codes, only: [:new, :create, :destroy, :index]
    resources :images, only: [:create, :destroy, :index]
    resources :sites
    resources :activities
    resources :days

    resources :visa_infos, only: [:new, :create, :destroy, :index]
    

    resources :invitation_codes do |invitation_code|
      get 'cancel', on: :member
    end
    
    resources :sessions, only: [:new, :create, :destroy]

    resources :sale_channels, only: [:create, :destroy, :update, :index]
    resources :sale_channel_maps, only: [:create, :destroy]

    get '/', to: 'plateforms#dashboard'
    get '/home', to: 'plateforms#home'
    get '/inbox', to: 'plateforms#inbox'
    get '/email_list', to: 'plateforms#email_list'
    get '/email_compose', to: 'plateforms#email_compose'
    get '/calendar', to: 'plateforms#calendar'
    get '/invitation_code_control', to: 'plateforms#invitation_code_control'
    get '/account_control', to: 'plateforms#account_control'

    get '/staff_index', to: 'plateforms#staff_index'
    get '/agent_index', to: 'plateforms#agent_index'
    get '/booking_index', to: 'plateforms#booking_index'
    get '/new_tour', to: 'plateforms#new_tour'
    get '/edit_tour', to: 'plateforms#edit_tour'
    get '/index_tour', to: 'plateforms#index_tour'

    get '/new_shelf', to: 'plateforms#new_shelf'
    get '/edit_shelf', to: 'plateforms#edit_shelf'
    get '/decorate_tour', to: 'plateforms#decorate_tour'
    get '/index_shelf', to: 'plateforms#index_shelf'

    get '/tag_control', to: 'plateforms#tag_control'
    get '/date_and_price_control', to: 'plateforms#date_and_price_control'
    get '/image_admin', to: 'plateforms#image_admin'
    get '/site_admin', to: 'plateforms#site_admin'
    get '/new_site_admin', to: 'plateforms#new_site_admin'

    get '/get_image_url', to: 'images#get_image_url'
    get '/get_image_list_by_site_id', to: 'sites#get_image_list_by_site_id'

    get '/departure_admin', to: 'plateforms#departure_admin'
    get '/price_admin', to: 'plateforms#price_admin'

    get '/sale_channels_admin', to: 'plateforms#sale_channels_admin'
    get '/agents_admin', to: 'plateforms#agents'
    get '/bookings_admin', to: 'plateforms#bookings_admin'
    get '/my_invitation_code', to: 'plateforms#my_invitation_code'

      match '/signup',  to: 'accounts#new', via: 'get'
      match '/signin',  to: 'sessions#new', via: 'get'
      match '/signout', to: 'sessions#destroy', via: 'delete'
  end
end

app/models/tour.rb
class Tour < ActiveRecord::Base

	has_many :days, :dependent => :destroy
	has_many :activities, through: :days
	has_many :departures, :dependent => :destroy
	has_many :prices, :through => :departures
	has_many :bookings, :through => :prices
	belongs_to :account
	belongs_to :sale_channel
	belongs_to :cover_img, :class_name => 'Image', :foreign_key => :cover_img_id
	belongs_to :icon_img, :class_name => 'Image', :foreign_key => :icon_img_id

	accepts_nested_attributes_for :days, :reject_if => lambda { |a| a[:number].blank? }, :allow_destroy => true

	def generate_itinerary(force=false)
		self.days.each do |day|
			day.generate_itinerary(force)
		end
	end

	def lowest_readable_price(account=nil)
		prices = readable_date_and_prices(account)
		if prices.nil?
			return nil
		else
			lowest_trade = prices.first.trade_price
			lowest_retail = prices.first.retail_price
			prices.each do |price|
				lowest_retail = price.retail_price if price.retail_price < lowest_retail
				lowest_trade = price.trade_price if price.trade_price < lowest_trade
			end
			return { trade: lowest_trade, retail: lowest_retail }
		end
	end

	def generate_title
		self.days.each do |day|
			day.generate_title
		end
	end

	def readable_date_and_prices(account=nil)
		self.date_and_prices
	end

	# return feature tags for isotope filtering
	def isotope_tags
		return "" if self.tour_type.blank?
		self.tour_type.split(/\s+/).map { |tag| "tag#{FeatureTag.find_by_name(tag).id}" }.join(" ")
	end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController

  def create
    @tour = Tour.new(tour_params)
    #@tour.tour_group = UserGroup.convert_name_string_to_id_string(params[:tour][:tour_group])
    @tour.tour_type = params[:tour][:tour_type]
    @tour.account_id = current_user.id

    if @tour.save
      @tour.generate_itinerary
      @tour.generate_title
      redirect_to '/admin#admin/index_tour.html'
    else
      redirect_to :back
    end
  end

  def update
    @tour = Tour.find_by_id(params[:id])
    unless @tour.nil?
      @tour.name = params[:tour][:name]
      @tour.description = params[:tour][:description]
     #@tour.tour_group = UserGroup.convert_name_string_to_id_string(params[:tour][:tour_group])
      @tour.tour_type = params[:tour][:tour_type]
      respond_to do |format|
        if @tour.update(tour_params)
          format.html { redirect_to '/admin#admin/index_tour.html' }
          format.json { head :no_content }
        else
          format.html { redirect_to :back }
          format.json { render json: @fee.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def index
    @tours = Tour.all
    render partial: "admin/tours/index_with_date", locals: { tours: @tours }, layout: false
  end

  def destroy
    @tour = Tour.find_by_id(params[:id])
    @tour.destroy
    redirect_to "/admin#admin/index_tour.html"
  end

  private
  def tour_params
    params.require(:tour).permit(:identifier, :flights, :expire_date, :cover_img_id, :icon_img_id, :name, :description, :sale_channel_id, :include, :exclude, :transportations, :notes, :visa, 
      :days_attributes => [:id, :tour_id, :number, :accommodation, :breakfast, :lunch, :dinner, :title, :itinerary, :_destroy, 
        :activities_attributes => [:id, :day_id, :time, :active_type, :site_id, :image_id, :short_des, :full_des, :_destroy] ] )
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  layout "lion"
  #before_action :store_location, except: [:show]
  before_action :set_tour, only: [:show, :show_docx]
  before_action :check_login, except: [:show, :show_docx]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
    if @tour.cover_img.nil?
      @cover_img = "default_tour_cover.jpg"
    else
      @cover_img = @tour.cover_img.photo.url(:original)
    end
    if @tour.icon_img.nil?
      @icon_img = "default_tour_icon.png"
    else
      @icon_img = @tour.icon_img.photo.url(:original)
    end
    @xml = Nokogiri::XML(@tour.erp_info)
    @features = Nokogiri::XML(@tour.erp_features).xpath('//feature').children.select{|e| e.cdata?}
    @itineraries = Nokogiri::XML(@tour.erp_info).xpath('//itineraryDay') 
    @trips = Nokogiri::XML(@tour.erp_more_info).xpath('//trip') 
    @images = Nokogiri::XML(@tour.erp_more_info).xpath('//image') 
    render layout: "front30"
  end

  # 为word转换而简化的html格式
  def show_docx
    @cover_img = "default_tour_cover.jpg"
    render layout: "docx"
  end

  def legacy
    @pictures = JSON.parse(@tour.content)["images"]
    render 'legacy', layout: 'application'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/admin/tours/_index.html.erb
<div class="jarviswidget jarviswidget-color-blue" id="wid-tours" data-widget-editbutton="false">

  <header>
    <span class="widget-icon"> <i class="fa fa-sitemap"></i> </span>
    <h2>线路列表</h2>

  </header>


  <div><!-- widget div-->


    <div class="jarviswidget-editbox"><!-- widget edit box --><!-- This area used as dropdown edit box -->


    </div><!-- end widget edit box -->


    <div class="widget-body"><!-- widget content -->
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>编号</th>
            <th>航班</th>
            <th>名称</th>
            <th>标签</th>
            <th>创建人</th>
            <th>销售渠道</th>
            <th>过期时间</th>
            <th>查看</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% tours.each do |tour| %>
          <tr>
            <td><%= tour.id %></td>
            <td><%= tour.flights %></td>
            <td><%= tour.name %></td>
            <td><%= tour.tour_type %></td>
            <td><%= tour.account.name %></td>
            <td><%= tour.sale_channel.name %><%#= UserGroup.convert_id_string_to_name_string(tour.tour_group) %></td>
            <td>
              <%= tour.expire_date.strftime("%b %d, %Y") %>
              <%= " <em>已过期</em>".html_safe if tour.expire_date < Time.now %>
            </td>
            <td>
              <%= link_to "手机", tour_path(tour), :target => "_blank" %>
              <%= link_to "PDF", tour_path(tour, :format => :pdf), :target => "_blank" %>
              <%= link_to "Word", tour_path(tour), :format => :docx, :target => "_blank" %>
            </td>
            <td>
              <a href="/admin#admin/edit_tour.html?id=<%= tour.id %>">修改</a>
              <%= link_to "删除", admin_tour_path(tour), :method => :delete %></td>
          </tr>
          <% end %>
        </tbody>
      </table>


    </div><!-- end widget content -->


  </div><!-- end widget div -->


</div>

app/views/admin/tours/_index_with_date.html.erb
<div class="jarviswidget jarviswidget-color-blue" id="wid-tours" data-widget-editbutton="false">

  <header>
    <span class="widget-icon"> <i class="fa fa-sitemap"></i> </span>
    <h2>团队列表</h2>

  </header>


  <div><!-- widget div-->


    <div class="jarviswidget-editbox"><!-- widget edit box --><!-- This area used as dropdown edit box -->


    </div><!-- end widget edit box -->


    <div class="widget-body"><!-- widget content -->
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>ERP编号</th>
            <!-- <th>航班</th> -->
            <th>名称</th>
            <th>销售渠道</th>
            <th>创建人</th>
            <th>出发日期</th>
            <th>过期时间</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% tours.each do |tour| %>
          <tr>
            <td><%= tour.identifier %></td>
            <!-- <td><%#= tour.flights %></td> -->
            <td><%= tour.name %></td>
            <td><%= tour.sale_channel.name%></td>
            <td><%= tour.account.name%></td>
            <td><%= link_to "/admin#" + admin_tour_departures_path(tour) do %>现有<%= tour.departures.count %>个<% end %></td>
            <td>
              <%= tour.expire_date.strftime("%b %d, %Y") %>
              <%= " <em>已过期</em>".html_safe if tour.expire_date < Time.now %>
            </td>
            <td><%= link_to "添加出发日期", "/admin#" + new_admin_tour_departure_path(tour) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>


    </div><!-- end widget content -->


  </div><!-- end widget div -->


</div>

app/views/admin/tours/_index_with_date_and_price.html.erb
<div class="jarviswidget jarviswidget-color-blue" id="wid-tours" data-widget-editbutton="false">

  <header>
    <span class="widget-icon"> <i class="fa fa-sitemap"></i> </span>
    <h2>线路列表</h2>

  </header>


  <div><!-- widget div-->


    <div class="jarviswidget-editbox"><!-- widget edit box --><!-- This area used as dropdown edit box -->


    </div><!-- end widget edit box -->


    <div class="widget-body"><!-- widget content -->
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>编号</th>
            <th>名称</th>
            <th>时间和价格</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% tours.each do |tour| %>
          <tr>
            <td><%= tour.id %></td>
            <td><%= tour.name %></td>
            <td><%= link_to "/admin#admin/date_and_price_control.html?tour_id=#{tour.id}" do %>现有<%= tour.date_and_prices.count %>个<% end %></td>
            <td><%= link_to "添加", "/admin#admin/date_and_price_control.html?tour_id=#{tour.id}&date_and_price_id=new" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>


    </div><!-- end widget content -->


  </div><!-- end widget div -->


</div>