config/routes.rb
Utour::Application.routes.draw do

  resources :date_and_prices

  resources :tours do
    get 'legacy', on: :member
    get 'show_docx', on: :member
  end

  resources :bookings do
    get 'account_specific_index', on: :collection
  end

  resources :accounts do
    get 'activate_show', on: :member
    post 'activate', on: :member
  end

  resources :agents

  resources :images, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :visa_infos, only: [:show]

  root 'front30#home'

  match '/signup',  to: 'accounts#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signout', to: 'sessions#destroy', via: 'get'

  match '/legacy/home', to: 'legacies#home', via: 'get'

  match '/legacy/group_tours', to: 'legacies#group_tours', via: 'get'
  match '/legacy/free_tours', to: 'legacies#free_tours', via: 'get'
  match '/legacy/assorted', to: 'legacies#assorted', via: 'get'
  match '/legacy/visa', to: 'legacies#visa', via: 'get'
  match '/legacy/my_booking', to: 'legacies#my_booking', via: 'get'
  match '/legacy/booking_status', to: 'legacies#booking_status', via: 'get'
  match '/legacy/info', to: 'legacies#info', via: 'get'
  match '/legacy/guide', to: 'legacies#guide', via: 'get'

  match '/wechat', to: 'wechats#check', via: 'get'
  match '/wechat', to: 'wechats#message', via: 'post'
  match '/wechat/debug', to: 'wechats#debug', via: 'get'

  match '/tiger', to: 'wechat_webs#tiger', via: 'get'
  match '/lion', to: 'wechat_webs#lion', via: 'get'
  match '/tiger/group_travel', to: 'wechat_webs#group_travel', via: 'get'
  match '/lion/group_travel', to: 'wechat_webs#group_travel', via: 'get'
  match '/lion/visa', to: 'wechat_webs#visa', via: 'get'
  match '/lion/trade', to: 'wechat_webs#trade', via: 'get'
  match '/lion/video', to: 'wechat_webs#video', via: 'get'
  match '/lion/contact', to: 'wechat_webs#contact', via: 'get'
  match '/lion/feedback', to: 'wechat_webs#feedback', via: 'post'
  match '/lion/diy', to: 'wechat_webs#diy', via: 'get'
  match '/lion/sale', to: 'wechat_webs#sale', via: 'get'
  match '/lion/guide', to: 'wechat_webs#guide', via: 'get'
  get '/lion/visa_detail', to: 'wechat_webs#visa_detail'

  get '/landing_page', to: 'front30#landing_page'

  get '/front30/home', to: 'front30#home'
  get '/front30/contact_about', to: 'front30#contact_about'
  get '/front30/about', to: 'front30#about'
  get '/front30/dm', to: 'front30#dm'
  get '/front30/video', to: 'front30#video'
  get '/front30/travel_guide', to: 'front30#travel_guide'
  get '/front30/group', to: 'front30#group'
  get '/front30/free', to: 'front30#free'
  get '/front30/onsale', to: 'front30#onsale'
  get '/front30/quick_booking', to: 'front30#quick_booking'

  

  namespace :admin do |admin|
    
    resources :accounts
    resources :admins
    resources :operators
    resources :sales
    resources :agents

    resources :tours do
      resources :departures do 
        resources :prices
      end
    end
    resources :bookings
    resources :user_groups
    resources :date_and_prices
    resources :shelves

    resources :feature_tag_connections, only: [:new, :create, :destroy, :index]
    resources :feature_tags, only: [:new, :create, :destroy, :index]
    resources :invitation_codes, only: [:new, :create, :destroy, :index]
    resources :images, only: [:create, :destroy, :index]
    resources :sites
    resources :activities
    resources :days

    resources :visa_infos, only: [:new, :create, :destroy, :index]
    

    resources :invitation_codes do |invitation_code|
      get 'cancel', on: :member
    end
    
    resources :sessions, only: [:new, :create, :destroy]

    resources :sale_channels, only: [:create, :destroy, :update, :index]
    resources :sale_channel_maps, only: [:create, :destroy]

    get '/', to: 'plateforms#dashboard'
    get '/home', to: 'plateforms#home'
    get '/inbox', to: 'plateforms#inbox'
    get '/email_list', to: 'plateforms#email_list'
    get '/email_compose', to: 'plateforms#email_compose'
    get '/calendar', to: 'plateforms#calendar'
    get '/invitation_code_control', to: 'plateforms#invitation_code_control'
    get '/account_control', to: 'plateforms#account_control'

    get '/staff_index', to: 'plateforms#staff_index'
    get '/agent_index', to: 'plateforms#agent_index'
    get '/booking_index', to: 'plateforms#booking_index'
    get '/new_tour', to: 'plateforms#new_tour'
    get '/edit_tour', to: 'plateforms#edit_tour'
    get '/index_tour', to: 'plateforms#index_tour'

    get '/new_shelf', to: 'plateforms#new_shelf'
    get '/edit_shelf', to: 'plateforms#edit_shelf'
    get '/decorate_tour', to: 'plateforms#decorate_tour'
    get '/index_shelf', to: 'plateforms#index_shelf'

    get '/tag_control', to: 'plateforms#tag_control'
    get '/date_and_price_control', to: 'plateforms#date_and_price_control'
    get '/image_admin', to: 'plateforms#image_admin'
    get '/site_admin', to: 'plateforms#site_admin'
    get '/new_site_admin', to: 'plateforms#new_site_admin'

    get '/get_image_url', to: 'images#get_image_url'
    get '/get_image_list_by_site_id', to: 'sites#get_image_list_by_site_id'

    get '/departure_admin', to: 'plateforms#departure_admin'
    get '/price_admin', to: 'plateforms#price_admin'

    get '/sale_channels_admin', to: 'plateforms#sale_channels_admin'
    get '/agents_admin', to: 'plateforms#agents'
    get '/bookings_admin', to: 'plateforms#bookings_admin'
    get '/my_invitation_code', to: 'plateforms#my_invitation_code'

      match '/signup',  to: 'accounts#new', via: 'get'
      match '/signin',  to: 'sessions#new', via: 'get'
      match '/signout', to: 'sessions#destroy', via: 'delete'
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_account, only: [:show, :edit, :update, :destroy, :activate_show]
  before_action :check_login, except: [:new, :create]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    #redirect_to activate_show_account_path(@account)
  end

  # GET /accounts/new
  def new
    @account = Account.new
    @role = params[:role]
    # if params[:user_class] == "trade"
    #   render 'accounts/new/trade', :locals => { "user_class_id" => Account.find_user_class_id_by_name(:trade) } 
    # elsif params[:user_class] == "staff"
    #   render 'accounts/new/staff', :locals => { "user_class_id" => Account.find_user_class_id_by_name(:staff) } 
    # else #params[:user_class] == "customer"
    #   render 'accounts/new/customer', :locals => { "user_class_id" => Account.find_user_class_id_by_name(:customer) } 
    # end
    render 'accounts/new'
  end

  # GET /accounts/activate_show
  def activate_show
    @contact = Account.sale_contact
    @sales = current_user.sales
  end

  # POST /accounts/activate
  def activate
    @account = current_user
    @sales = current_user.sales
    if @account.present?
      code = InvitationCode.find_by_code(params[:account][:activation_code])
      if code.present? == false
        @account.errors.add(:activation_code, '该邀请码无效') 
        render 'activate_show'
      elsif code.status[:state] != :ok
        #puts ">>>>>>>>>>>>>>>>>>#{code.status}"
        @account.errors.add(:activation_code, code.status[:message])
        render 'activate_show'
      # elsif code.used
      #   @account.errors.add(:activation_code, '该邀请码已被使用请填入其他激活码') 
      #   render activate_show_account_path(account)
      # elsif Date.today > code.expire_time
      #   @account.errors.add(:activation_code, '该邀请码已过期请重新申请') 
      #   render activate_show_account_path(account)
      elsif code.user_class_id != @account.user_class_id
        @account.errors.add(:activation_code, "该邀请码非同业注册邀请码")
        render 'activate_show'
      else
        @account.update_attribute(:sale_channel, code.sale_channel)
        @account.update_attribute(:active, true)

        SaleAgent.new(sale_id: code.account.id, agent_id: @account.id).save
        
        code.use(@account)
        flash.now[:notice] = "添加新销售成功"
        render 'activate_show'
      end
    else
      render text: "WECHAT_ID #{params[:wechat_id]} not found"
    end
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  # 注册同行账号
  def create
    @account = Account.new(account_params)
    if @account.gender == 2
      @account.gender = "女"
    else
      @account.gender = "男"
    end
    @account.user_class_id = 5 # 5 = 同行
    @account.sale_channel = SaleChannel.find_by_name("直客渠道")

    # if @account.is_trade == "1"
    #   @account.active = false
    #   @account.set_trade
    # else
    #   @account.active = true
    #   @account.set_customer
    # end

    respond_to do |format|
      if @account.save
       # if @account.is_trade == "1"
          WexchatMailer.trader_welcome_email(@account).deliver
       # else
       #   WexchatMailer.customer_welcome_email(@account).deliver
       # end
        format.html {
          sign_in @account
          #puts ">>>>>>>>>> #{@account.user_class_id} #{@account.user_class_id == 3} #{@account.user_class_id == '3'} #{@account.trade?} >>>>>>>>>>>> #{activate_show_account_path(@account)} "
          if !@account.company_name.blank?
            redirect_to activate_show_account_path(@account), notice: '新用户申请成功'
          else
            redirect_back_or_default
          end
          # if @account.trade?

          #   redirect_to activate_show_account_path(@account), notice: '新用户申请成功'
          # else
            
          #   redirect_back_or_default
          # end
        }
        #format.json { render action: 'show', status: :created, location: @account }
      else
        format.html {
          # if @account.user_class_id == Account.find_user_class_id_by_name(:trade)
          #   render 'accounts/new/trade', :locals => { "user_class_id" => Account.find_user_class_id_by_name(:trade) } 
          # elsif @account.user_class_id == Account.find_user_class_id_by_name(:staff)
          #   render 'accounts/new/staff', :locals => { "user_class_id" => Account.find_user_class_id_by_name(:staff) } 
          # else #params[:user_class] == "customer"
          #   render 'accounts/new/customer', :locals => { "user_class_id" => Account.find_user_class_id_by_name(:customer) } 
          # end
          render 'accounts/new'
        }
        #format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:company_name, :name, :mobile, :email, :gender, :wechat_id, :password, :password_confirmation, :memory_token)
    end
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create]

  def new
    @account = Account.new
    render layout: false
  end

  # 注册后台用户: 系统管理, 管理, 销售和操作
  def create
    @account = Account.new(account_params)
    if params[:gender] == 2
      @account.gender = "女"
    else
      @account.gender = "男"
    end
    
    invitation_code = InvitationCode.find_by_code(params[:invitation_code])
    if invitation_code.nil?
      @account.errors[:invitation_code] = "注册码无效"
      render 'new', layout: false
    elsif invitation_code.user_class_id != @account.user_class_id
      @account.errors[:invitation_code] = "该注册码不匹配所申请注册用户类型"
      render 'new', layout: false
    elsif invitation_code.status[:state] != :ok
      @account.errors[:invitation_code] = "注册码#{invitation_code.status[:message]}"
      render 'new', layout: false
    else
      @account.active = true
      @account.user_class_id = invitation_code.user_class_id
      @account.user_group_id = invitation_code.user_group_id
      @account.sale_channel_id = invitation_code.sale_channel_id
      if @account.save
        invitation_code.use(@account)
        WexchatMailer.staff_welcome_email(@account).deliver
        respond_to do |format|
          format.html {
            invitation_code.use(@account)
            sign_in @account
            redirect_to '/admin#admin/home.html'
          }
        end
      else
        render 'new', layout: false
      end
    end
  end

  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @account = Account.find_by_id(params[:id])
    @account.destroy
    respond_to do |format|
      format.html { redirect_to '/admin#admin/account_admin.html' }
      format.js
    end
  end

  def index
    respond_to do |format|
      format.js {
        if params[:type] == "staff"
          @accounts = Account.where("user_class_id <= 4")
          #puts ">>>>>>>>#{@accounts.count}"
          @accounts.map! do |account|
            #puts "account = #{account.name}"
            if account.id == current_user.id || UserGroupMap.where(up_id: current_user.user_group_id, down_id: account.user_group_id).count > 0
              #puts "OK"
              account
            else
              #puts "NO"
              nil
            end
          end
          #puts ">>>#{@account}"
          @accounts.compact!
          render 'staff_index'
        elsif params[:type] == "agent"
          @accounts = Account.where("user_class_id > 4")
          @accounts.map! do |account|
            #puts "account = #{account.name}"
            if account.id == current_user.id || UserGroupMap.where(up_id: current_user.user_group_id, down_id: account.user_group_id).count > 0
              #puts "OK"
              account
            else
              #puts "NO"
              nil
            end
          end
          #puts ">>>#{@account}"
          @accounts.compact!
          render 'agent_index'
        end
      }
    end
  end

  
  private
  def account_params
    params.require(:account).permit(:user_class_id, :name, :mobile, :email, :gender, :wechat_id, :password, :password_confirmation, :memory_token)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin/accounts_helper.rb
module Admin::AccountsHelper
end

app/views/accounts/new/_agent_items.html.erb
<div class="form-group">
  <%= f.label :company_name, '公司名称'%>
  <% if @account.present? && @account.errors[:name] %>
  <% @account.errors[:name].each do |msg| %>
  <%= render inline: "<span class=\"inline_error_message\">#{msg}</span><br/>" %>
  <% end %>
  <% end %>
  <%= f.text_field :company_name, :placeholder => "请填写您的公司/门店名称", :class => "form-control" %>
</div>

app/views/accounts/new/_form.html.erb
<%= form_for :account, url: accounts_path, :html => {:role => "form", :class => "form-horizontal"} do |f| %>

<div class="form-group">
  <%= f.label :name, '姓名'%>
  <% if @account.present? && @account.errors[:name] %>
  <% @account.errors[:name].each do |msg| %>
  <%= render inline: "<span class=\"inline_error_message\">#{msg}</span><br/>" %>
  <% end %>
  <% end %>
  <%= f.text_field :name, :placeholder => "请务必填写真实姓名", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :mobile, '手机' %>
  <% if @account.present? && @account.errors[:mobile] %>
  <% @account.errors[:mobile].each do |msg| %>
  <%= render inline: "<span class=\"inline_error_message\">#{msg}</span><br/>" %>
  <% end %>
  <% end %>
  <%= f.text_field :mobile, :placeholder => "11位国内手机号码", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :email, '电子邮箱' %>
  <% if @account.present? && @account.errors[:email] %>
  <% @account.errors[:email].each do |msg| %>
  <%= render inline: "<span class=\"inline_error_message\">#{msg}</span><br/>" %>
  <% end %>
  <% end %>
  <%= f.text_field :email, :placeholder => "例如: 12345@qq.com", :type => "email", :class => "form-control" %>
</div>

<div class="form-group" >
  <%= f.label :gender, '性别' %>
  <% if params[:account].nil? %>
  <%= f.check_box :gender, :checked => true, :class => "switch", :"data-on-label" => "男", :"data-off-label" => "女", :"data-on" => "primary", :"data-off" => "danger", :"data-label-icon" => "glyphicon glyphicon-cog" %>
  <% else %>
  <%= f.check_box :gender, :checked => params[:account][:gender] == "0" ? false : true, :class => "switch", :"data-on-label" => "男", :"data-off-label" => "女", :"data-on" => "primary", :"data-off" => "danger", :"data-label-icon" => "glyphicon glyphicon-cog" %>
  <% end %>
</div>


<%#= render partial: "accounts/new/agent_items" if role == "agent" %>
<%#= render partial: "accounts/new/retail_items" if role == "retail" %>

<% if role=="agent" %>
<div class="form-group">
  <%= f.label :company_name, '公司名称'%>
  <% if @account.present? && @account.errors[:name] %>
  <% @account.errors[:name].each do |msg| %>
  <%= render inline: "<span class=\"inline_error_message\">#{msg}</span><br/>" %>
  <% end %>
  <% end %>
  <%= f.text_field :company_name, :placeholder => "请填写您的公司/门店名称", :class => "form-control" %>
</div>
<% end %>



<!-- <div class="form-group" >
  <%#= f.check_box :is_trade %>
  <%#= f.label :is_trade, '我是旅行社同业(门店，二级经销商等)' %> <p>注意: 同业注册在本公司验证前不能报名！</p>
</div> -->

<div class="form-group">
  <%= f.label :password, '密码' %>
  <% if @account.present? && @account.errors[:password] %>
  <% @account.errors[:password].each do |msg| %>
  <%= render inline: "<span class=\"inline_error_message\">#{msg}</span><br/>" %>
  <% end %>
  <% end %>
  <%= f.password_field :password, :class => "form-control", :placeholder => "至少6位" %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation, '确认密码' %>
  <% if @account.present? && @account.errors[:password_confirmation] %>
  <% @account.errors[:password_confirmation].each do |msg| %>
  <%= render inline: "<span class=\"inline_error_message\">#{msg}</span><br/>" %>
  <% end %>
  <% end %>
  <%= f.password_field :password_confirmation, :class => "form-control", :placeholder => "重复密码" %>
</div>

<div class="form-group">
  <%= f.submit "注册", :class => "btn btn-default btn-success full_width" %>
</div>
<% end %>

app/views/accounts/new/customer.html.erb
<% content_for :stylesheet do %>
<%= stylesheet_link_tag "accounts", media: "all", "data-turbolinks-track" => true %>
<% end %>
<div class="container">
    <div class="row account_new">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <h2>请填写您的个人信息</h2>

        <%= render partial: 'accounts/new/form', user_class_id: Account.find_user_class_id_by_name(:customer) %>

      </div>
    
  </div>

  <%#= link_to 'Back', accounts_path %>
</div>

<script>
$(function() {
  $('.switch').bootstrapSwitch();
});
</script>

app/views/accounts/new/trade.html.erb
<% content_for :stylesheet do %>
<%= stylesheet_link_tag "accounts", media: "all", "data-turbolinks-track" => true %>
<% end %>
<div class="container">
    <div class="row account_new">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <h2>同业注册</h2>
        <%# puts ".............   #{Account.find_user_class_id_by_name(:trade)}" %>
        <%= render partial: 'accounts/new/form', :locals => { user_class_id: Account.find_user_class_id_by_name(:trade) }  %>

      </div>
    
  </div>

  <%#= link_to 'Back', accounts_path %>
</div>

<script>
$(function() {
  $('.switch').bootstrapSwitch();
});
</script>