config/routes.rb
Utour::Application.routes.draw do

  resources :date_and_prices

  resources :tours do
    get 'legacy', on: :member
    get 'show_docx', on: :member
  end

  resources :bookings do
    get 'account_specific_index', on: :collection
  end

  resources :accounts do
    get 'activate_show', on: :member
    post 'activate', on: :member
  end

  resources :agents

  resources :images, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :visa_infos, only: [:show]

  root 'front30#home'

  match '/signup',  to: 'accounts#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signout', to: 'sessions#destroy', via: 'get'

  match '/legacy/home', to: 'legacies#home', via: 'get'

  match '/legacy/group_tours', to: 'legacies#group_tours', via: 'get'
  match '/legacy/free_tours', to: 'legacies#free_tours', via: 'get'
  match '/legacy/assorted', to: 'legacies#assorted', via: 'get'
  match '/legacy/visa', to: 'legacies#visa', via: 'get'
  match '/legacy/my_booking', to: 'legacies#my_booking', via: 'get'
  match '/legacy/booking_status', to: 'legacies#booking_status', via: 'get'
  match '/legacy/info', to: 'legacies#info', via: 'get'
  match '/legacy/guide', to: 'legacies#guide', via: 'get'

  match '/wechat', to: 'wechats#check', via: 'get'
  match '/wechat', to: 'wechats#message', via: 'post'
  match '/wechat/debug', to: 'wechats#debug', via: 'get'

  match '/tiger', to: 'wechat_webs#tiger', via: 'get'
  match '/lion', to: 'wechat_webs#lion', via: 'get'
  match '/tiger/group_travel', to: 'wechat_webs#group_travel', via: 'get'
  match '/lion/group_travel', to: 'wechat_webs#group_travel', via: 'get'
  match '/lion/visa', to: 'wechat_webs#visa', via: 'get'
  match '/lion/trade', to: 'wechat_webs#trade', via: 'get'
  match '/lion/video', to: 'wechat_webs#video', via: 'get'
  match '/lion/contact', to: 'wechat_webs#contact', via: 'get'
  match '/lion/feedback', to: 'wechat_webs#feedback', via: 'post'
  match '/lion/diy', to: 'wechat_webs#diy', via: 'get'
  match '/lion/sale', to: 'wechat_webs#sale', via: 'get'
  match '/lion/guide', to: 'wechat_webs#guide', via: 'get'
  get '/lion/visa_detail', to: 'wechat_webs#visa_detail'

  get '/landing_page', to: 'front30#landing_page'

  get '/front30/home', to: 'front30#home'
  get '/front30/contact_about', to: 'front30#contact_about'
  get '/front30/about', to: 'front30#about'
  get '/front30/dm', to: 'front30#dm'
  get '/front30/video', to: 'front30#video'
  get '/front30/travel_guide', to: 'front30#travel_guide'
  get '/front30/group', to: 'front30#group'
  get '/front30/free', to: 'front30#free'
  get '/front30/onsale', to: 'front30#onsale'
  get '/front30/quick_booking', to: 'front30#quick_booking'

  

  namespace :admin do |admin|
    
    resources :accounts
    resources :admins
    resources :operators
    resources :sales
    resources :agents

    resources :tours do
      resources :departures do 
        resources :prices
      end
    end
    resources :bookings
    resources :user_groups
    resources :date_and_prices
    resources :shelves

    resources :feature_tag_connections, only: [:new, :create, :destroy, :index]
    resources :feature_tags, only: [:new, :create, :destroy, :index]
    resources :invitation_codes, only: [:new, :create, :destroy, :index]
    resources :images, only: [:create, :destroy, :index]
    resources :sites
    resources :activities
    resources :days

    resources :visa_infos, only: [:new, :create, :destroy, :index]
    

    resources :invitation_codes do |invitation_code|
      get 'cancel', on: :member
    end
    
    resources :sessions, only: [:new, :create, :destroy]

    resources :sale_channels, only: [:create, :destroy, :update, :index]
    resources :sale_channel_maps, only: [:create, :destroy]

    get '/', to: 'plateforms#dashboard'
    get '/home', to: 'plateforms#home'
    get '/inbox', to: 'plateforms#inbox'
    get '/email_list', to: 'plateforms#email_list'
    get '/email_compose', to: 'plateforms#email_compose'
    get '/calendar', to: 'plateforms#calendar'
    get '/invitation_code_control', to: 'plateforms#invitation_code_control'
    get '/account_control', to: 'plateforms#account_control'

    get '/staff_index', to: 'plateforms#staff_index'
    get '/agent_index', to: 'plateforms#agent_index'
    get '/booking_index', to: 'plateforms#booking_index'
    get '/new_tour', to: 'plateforms#new_tour'
    get '/edit_tour', to: 'plateforms#edit_tour'
    get '/index_tour', to: 'plateforms#index_tour'

    get '/new_shelf', to: 'plateforms#new_shelf'
    get '/edit_shelf', to: 'plateforms#edit_shelf'
    get '/decorate_tour', to: 'plateforms#decorate_tour'
    get '/index_shelf', to: 'plateforms#index_shelf'

    get '/tag_control', to: 'plateforms#tag_control'
    get '/date_and_price_control', to: 'plateforms#date_and_price_control'
    get '/image_admin', to: 'plateforms#image_admin'
    get '/site_admin', to: 'plateforms#site_admin'
    get '/new_site_admin', to: 'plateforms#new_site_admin'

    get '/get_image_url', to: 'images#get_image_url'
    get '/get_image_list_by_site_id', to: 'sites#get_image_list_by_site_id'

    get '/departure_admin', to: 'plateforms#departure_admin'
    get '/price_admin', to: 'plateforms#price_admin'

    get '/sale_channels_admin', to: 'plateforms#sale_channels_admin'
    get '/agents_admin', to: 'plateforms#agents'
    get '/bookings_admin', to: 'plateforms#bookings_admin'
    get '/my_invitation_code', to: 'plateforms#my_invitation_code'

      match '/signup',  to: 'accounts#new', via: 'get'
      match '/signin',  to: 'sessions#new', via: 'get'
      match '/signout', to: 'sessions#destroy', via: 'delete'
  end
end

app/controllers/wechat_webs_controller.rb
class WechatWebsController < ApplicationController
  #before_action :store_location, only: [:trade]
  before_action :check_login, only: [:group_travel, :diy, :trade, :booking, :sale]
	layout "lion"
  
  def tiger
  	render 'tiger', :layout => 'tiger'
  end

  def lion
    @slides = Image.where(image_type: "海报")
    render 'lion', layout: "application"
  end

  # 签证资料
  def visa
    
  end

  # 团队行程
  def group_travel
  	@tours = Tour.where("expire_date > ? AND departure_city = ?", Time.now, "北京")
    @root = JSON.parse Shelf.find_by_name("团队行程").rack
    @set = ["跟团游"]
  end

  # 自由行
  def diy
    @tours = Tour.where("expire_date > ?", Time.now)
    @root = JSON.parse Shelf.find_by_name("自由行").rack
    @set = ["自由行"]
    render 'group_travel'
  end

  # 同业动态
  def trade
    account = trade_or_staff?
    puts ">>>>>>>>>>>>>>> #{account}"
    if account.nil? # 要求登录
      redirect_to :controller=> 'sessions', :action => 'new', :user_class => 'trade'
    else
      puts ">>>>>>>>>>>>>>>>>>#{account.active} >>>>>>>>>>>>>>>>>>>#{activate_show_account_path(account)}"
      redirect_to activate_show_account_path(account) if account.active == false # 要求注册码激活
    end
  end

  #出团视频
  def video
  end

  # 我的众信
  def booking
  end


  def status
  end

  # 出团说明
  def info
  end

  # 签证攻略
  def visa_guide
  end

  # 出行攻略
  def travel_guide
  end

  # 特别推荐
  def sale
    account = trade_or_staff?
    puts ">>>>>>>>>>>>>>> #{account}"
    if account.nil? # 要求登录
      redirect_to :controller=> 'sessions', :action => 'new', :user_class => 'trade'
    else
      redirect_to '/images/dm.jpg'
      #puts ">>>>>>>>>>>>>>>>>>#{account.active} >>>>>>>>>>>>>>>>>>>#{activate_show_account_path(account)}"
      #redirect_to activate_show_account_path(account) if account.active == false # 要求注册码激活
    end
    # @tours = Tour.all
    # @root = JSON.parse Shelf.find_by_name("特惠行程").rack
    # @set = ["特惠行程"]
    # render 'group_travel'
  end

  def contact
    @account = current_user
  end

  def feedback
    WexchatMailer.contact_message(params[:name], params[:contact], params[:content]).deliver
    @account = current_user
    @message = "您的问题已提交, 我们会尽快与您联系."
    render 'contact'
  end


  private
  

end

app/helpers/wechat_webs_helper.rb
module WechatWebsHelper
end

app/views/wechat_webs/_left_links.html.erb
<li><a href="/lion/group_travel">团队行程</a></li>
<li><a href="/lion/diy">自由行程</a></li>
<li><a href="/lion/visa">签证</a></li>
<li><a href="/lion/sale">精品推荐</a></li>
<li><a href="/lion/guide">出行攻略</a></li>
<li><a href="/lion/trade">同业交流</a></li>
<li><a href="/lion/contact">联系我们</a></li>

app/views/wechat_webs/contact.html.erb
<% content_for :left_links do %>
<% render "front30/left_links" %>
<% end %>

<div class="container lion">
	<div id="contact">
		<h3 style="text-align: center">联系我们</h3>
		<br />

		<% if @message.present? %>
		<div class="alert alert-success">
			<%= @message %>
		</div>
		<% end %>

		<%= form_for :contact, url: lion_feedback_path, :html => {:role => "form"} do |f| %>
		<form role="form">
			<div class="form-group">
				<label for="name">您的姓名</label>
				<input type="text" class="form-control" id="name" placeholder="请输入您的姓名" <%= "value=#{@account.name}" if @account.present? %> name="name">
			</div>
			<div class="form-group">
				<label for="contact">您的电话或邮箱</label>
				<input type="text" class="form-control" id="contact" placeholder="请输入您最方便的联系方式" <%= "value=#{@account.mobile}" if @account.present? %> name="contact">
			</div>

			<div class="form-group">
				<label for="content">咨询内容</label>
				<textarea rows="5" id="content" class="form-control" placeholder="请输入您咨询的内容" name="content" ></textarea>
			</div>
			
			<button type="submit" class="btn btn-default">提交</button>
			<%= link_to "返回首页", root_url, class: "btn btn-default btn-primary" %>
		<% end %>
	</div>
</div>

app/views/wechat_webs/group_travel.html.erb
<% content_for :left_links do %>
<% render "left_links" %>
<% end %>



<div class="container lion">
  <div class="head">
    <% header = Image.where(image_type: "海报").to_a.sample %>
    <%= image_tag header.nil? ? "default_slide.jpg" : header.photo.url(:original) , alt: "picture", style: "width:100%" %>
  </div>




  <div class="group_travel_menu">
    <% if !@root["members"].empty? %>
    <div id="<%= @root["members"].object_id %>" class="accordion-group panel-group">

      <% @root["members"].each do |one| %><!-- level one loop -->
      <% @set.push one["name"] %>
      <div class="panel panel-primary">
        <div class="panel-heading whole_heading_link">
          <a data-toggle="collapse" data-parent="#<%= @root["members"].object_id %>" href="#<%= one.object_id %>">
            <h2 class="panel-title">
              <%= one["name"] %>
            </h2>
          </a>
        </div>
        <div id="<%= one.object_id %>" class="panel-collapse collapse">
          <div class="panel-body menu_body_1" style="padding: 5px">

            <% if !one["members"].empty? %>
            <div id="<%= one["members"].object_id %>" class="panel-group">

              <% one["members"].each do |two| %><!-- level two loop -->
              <% @set.push two["name"] %>
              <div class="panel panel-success">
                <div class="panel-heading whole_heading_link">                  
                  <a data-toggle="collapse" data-parent="#<%= one["members"].object_id %>" href="#<%= two.object_id %>">
                    <h3 class="panel-title">
                      <%= two["name"] %>                    
                    </h3>
                  </a>
                </div>
                <div id="<%= two.object_id %>" class="panel-collapse collapse">
                  <div class="panel-body menu_body_2" style="padding: 0">
                    <%# 除去不符合标签的团队 %>
                    <% tours = @tours.select { |tour| (@set & tour.tour_type.split) == @set } %>

                    <%# 除去过期的团队 !!! filter moved to controller level !!! %>
                    <%# tours = tours.select { |tour| tour.expire_date > Time.now } %>                    
                    
                    <%# 除去没有权限查看的团队 %>
                    <% array = [] %>
                    <% tours.each do |tour| %>

                    <% if tour.sale_channel_id == current_user.sale_channel_id || SaleChannelMap.where(up: tour.sale_channel_id, down: current_user.sale_channel_id).count > 0 %>

                    <%# puts ">> #{tour.name} >> #{tour.sale_channel_id} >>>>>>>>>>>> #{current_user.sale_channel_id} >>>>>>>>> OK" %>
                    <% array.push tour %>
                    <% end # end if %>

                    <% end # end each %>
                    <% tours = array %>


                    <% if !tours.empty? %>
                    <%= render partial: 'tour_list', locals: { tours: tours } %>
                    <% else %>
                    暂无
                    <% end %>

                  </div>
                </div>
              </div>
              <% @set.pop %>          
              <% end %><!-- end level two loop -->

            </div>
            <% else %>
            <% tours = @tours.select { |tour| (@set & tour.tour_type.split) == @set } %>
            <% if !tours.empty? %>
            <%= render partial: 'tour_list', locals: { tours: tours } %>
            <% else %>
            暂无
            <% end %>

            <% end %>
          </div>
        </div>
      </div>
      <% @set.pop %>
      <% end %><!-- end level one loop -->

    </div>
    <% else %>
    <h3>本业没有内容</h3>
    <% end %>
  </div>

app/views/wechat_webs/guide.html.erb
<% content_for :stylesheet do %>
<% end %>

<% content_for :left_links do %>
<% render "left_links" %>
<% end %>

<div class="container lion">
  <div class="head">
    <%= image_tag "legacy/carousel/le_1.jpg", alt: "picture", style: "width:100%" %>
  </div>
  <div class="trade">
    <div class="list-group">
      <a href='http://dp.sina.cn/dpool/tools/forex/index.php?vt=4&pos=95&cid=768' class="list-group-item">货币兑换</a>
      <a href='http://dp.sina.cn/dpool/tools/flight/index.php?pos=81&vt=4' class="list-group-item">航班动态</a>
      <a href='http://fanyi.baidu.com/#auto/en/' class="list-group-item">多种语言翻译</a>
      <a href='http://m.mafengwo.cn/mdd/' class="list-group-item">旅游攻略</a>
      <a href='http://weather1.sina.cn/?vt=4' class="list-group-item">世界天气</a>
    </div>
  </div>
</div>

app/views/wechat_webs/lion.html.erb
<% content_for :stylesheet do %>
<%= stylesheet_link_tag "metro-bootstrap", media: "all", "data-turbolinks-track" => true %>
<% end %>
<div class="container lion">

  <div class="head">
    <div id="legacy-home-carousel" class="carousel slide" data-ride="carousel">

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <% if @slides.empty? %>
        <div class="item active">
          <%= image_tag "default_slide.jpg", alt: "欢迎访问UTOUR-众信旅游微信分销平台", style:"width:100%" %>
        </div>
        <% else %>
        <% @slides.each do |slide| %>
        <% if slide == @slides.first %>
        <div class="item active">
          <%= image_tag slide.photo.url( :original ), alt: slide.name, style:"width:100%" %>
        </div>
        <% else %>
        <div class="item">
          <%= image_tag slide.photo.url( :original ), alt: slide.name, style:"width:100%"%>
        </div>
        <% end # end if %>
        <% end # end each %>
        <% end # end if %>
      </div>

      <!-- Controls -->
      <a class="left carousel-control hidden-xs hidden-sm" href="#legacy-home-carousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control hidden-xs hidden-sm" href="#legacy-home-carousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
    <div style="width: 100%; height:20px; background-color: #000">
      <p id="carousel-text" style="color: #fff;text-align: center">
        <% if @slides.empty? %>
        欢迎访问UTOUR-众信旅游微信分销平台
        <% else %>
        <%= @slides.first.description %>
        <% end %>
      </p>
    </div>
  </div>


  <div class="tile_menu">

    <div class="row">
      <div class="col-xs-5 col-sm-5 col-md-5" style="padding: 5px; height: 100px">
        <div class="thumbnail tile tile-amethyst" style="width: 100%; height: 100%; margin: 0">
          <a href="/lion/group_travel" >
            <h1 class="tile_title">团队行程</h1>
            <i class="fa fa-users fa-3x" style="color: #fff"></i>
          </a>
        </div>
      </div>

      <div class="col-xs-4 col-sm-4 col-md-4" style="padding: 5px; height: 100px">
        <div class="thumbnail tile tile-peter-river" style="width: 100%; height: 100%; margin: 0">
          <a href="lion/diy" >
            <h1 class="tile_title">自由行程</h1>
            <i class="fa fa-globe fa-3x" style="color: #fff"></i>
          </a>
        </div>
      </div>
      <div class="col-xs-3 col-sm-3 col-md-3" style="padding: 5px; height: 100px">
        <div class="thumbnail tile" style="background-color: #0000FF; width: 100%; height: 100%; margin: 0">
          <a href="/lion/visa" >
            <h1 class="tile_title">签证</h1>
            <i class="fa fa-clipboard fa-3x" style="color: #fff"></i>
          </a>
        </div>
      </div>
    </div>

    <div class="row" style="margin-top: 0px">
      <div class="col-xs-7 col-sm-7 col-md-7" style="padding: 5px; height: 115px">
        <div class="thumbnail tile tile-orange" style="width: 100%; height: 100%; margin: 0">
          <a href="/lion/sale" >
            <h1 class="tile_title">精品DM单专区</h1>
            <i class="fa fa-shopping-cart fa-3x" style="color: #fff"></i>
          </a>
        </div>
      </div>
      <div class="col-xs-5 col-sm-5 col-md-5" style="padding: 5px; height: 115px">
        <div class="thumbnail tile" style="background-color: white; width: 100%; height: 100%; margin: 0">
          <a href="/bookings">
            <%= image_tag "logo.png", alt: "", class: "menu_company_icon" %>
            <h1 style="color: #f39c12; font-size: 20px; margin: 0">我的众信</h1>
          </a>
        </div>
      </div>

    </div>

    <div class="row" style="margin-top: 0px">
      <div class="col-xs-4 col-sm-4 col-md-4" style="padding: 5px; height: 100px">
        <div class="thumbnail tile tile-sun-flower" style="width: 100%; height: 100%; margin: 0">
          <a href="/lion/sale" >
            <h1 class="tile_title">出行攻略</h1>
            <i class="fa fa-compass fa-3x fa-spin" style="color: #fff"></i>
          </a>
        </div>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4" style="padding: 5px; height: 100px">
        <div class="thumbnail tile tile-carrot" style="width: 100%; height: 100%; margin: 0">
          <a href="/lion/video" >
            <h1 class="tile_title">出团视频说明</h1>
            <i class="fa fa-youtube-play fa-3x" style="color: #fff"></i>
          </a>
        </div>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4" style="padding: 5px; height: 100px">
        <div class="thumbnail tile tile-pomegranate" style="width: 100%; height: 100%; margin: 0">
          <a href="/lion/contact" >
            <h1 class="tile_title">联系我们</h1>
            <i class="fa fa-envelope fa-3x" style="color: #fff"></i>
          </a>
        </div>
      </div>
    </div>
  </div>

</div>

<script type="text/javascript">
$(document).ready(function() {  
 $("#legacy-home-carousel").swiperight(function() {  
  $(this).carousel('prev');  
});  
 $("#legacy-home-carousel").swipeleft(function() {  
  $(this).carousel('next');  
});

$('#legacy-home-carousel').on('slid.bs.carousel', function () {
  $('#carousel-text').text($('.active img').attr("alt"));
});
});  
</script>

app/views/wechat_webs/sale.html.erb
<% content_for :stylesheet do %>
<% end %>

<% content_for :left_links do %>
<% render "left_links" %>
<% end %>

<div class="container lion">
  <div class="head">
    <%= image_tag "legacy/carousel/le_0.jpg", alt: "picture", style: "width:100%" %>
  </div>
  <embed src="http://player.youku.com/player.php/sid/XMzI2NTc4NTMy/v.swf" 
  width="480" height="400" 
  type="application/x-shockwave-flash">
</embed>
<div class="">

  <br/>
  <div class="jumbotron">
    <h1>最新DM单</h1>
    <p></p>
    <p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p>
  </div>
  <div class="list-group">
    <a href="#" class="list-group-item">
      Cras justo odio
    </a>
    <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
    <a href="#" class="list-group-item">Morbi leo risus</a>
    <a href="#" class="list-group-item">Porta ac consectetur ac</a>
    <a href="#" class="list-group-item">Vestibulum at eros</a>
  </div>
</div>
</div>

app/views/wechat_webs/tiger.html.erb
<div class="container">

  <div class="tile-group seven" style="float: none; margin: 0 auto; padding: 0">
    <%= image_tag "legacy/carousel/le_0.jpg", alt: "picture", style: "width:100%" %>
    <div style="width:100%; height: 20px; background-color: #000"></div>
  </div>


  <div class="tile-group seven" style="float: none; margin: 0 auto;">
    <a class="tile triple double-vertical bg-cyan">
      <div class="tile-content icon">
        <span class="icon-bus"></span>
      </div>
      <div class="brand">
        <div class="label">Store</div>
      </div>
    </a>

    <div class="tile double double-vertical bg-darkCyan">
      <i class="icon-rocket"></i>
<span class="icon-rocket"></span>
    </div>

    <div class="tile double double-vertical bg-indigo">
    </div>

    <div class="tile quadro double-vertical bg-lightGreen">
    </div>

    <div class="tile triple double-vertical bg-white">
    </div>

    <div class="tile double double-vertical bg-amber">
    </div>

    <div class="tile triple double-vertical bg-orange">
    </div>

    <div class="tile double double-vertical bg-magenta">
    </div>
  </div>



  icon<i class="icon-rocket on-right on-left"
    style="background: red;
           color: white;
           padding: 10px;
           border-radius: 50%"></i>rocket
</div>

app/views/wechat_webs/trade.html.erb
<% content_for :stylesheet do %>
<% end %>

<% content_for :left_links do %>
<% render "left_links" %>
<% end %>

<div class="container lion">
  <div class="head">
    <%= image_tag "legacy/carousel/le_0.jpg", alt: "picture", style: "width:100%" %>
  </div>
  <div class="trade">
    <div class="list-group">
      <a href="#" class="list-group-item">
        Cras justo odio
      </a>
      <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
      <a href="#" class="list-group-item">Morbi leo risus</a>
      <a href="#" class="list-group-item">Porta ac consectetur ac</a>
      <a href="#" class="list-group-item">Vestibulum at eros</a>
    </div>
  </div>
</div>

app/views/wechat_webs/video.html.erb
<% content_for :stylesheet do %>
<% end %>

<% content_for :left_links do %>
<% render "left_links" %>
<% end %>

<div class="container lion">
  <div class="head">
    <%= image_tag "legacy/carousel/le_0.jpg", alt: "picture", style: "width:100%" %>
  </div>
  <div class="trade">
    <div class="list-group">
      <a href="http://v.youku.com/v_show/id_XMTkwMTcyODk2.html" class="list-group-item">欧洲五国</a>
      <a href="http://v.youku.com/v_show/id_XMTkwMTcxNzY0.html" class="list-group-item">芬兰、瑞士、挪威和芬兰</a>
      <a href="http://v.youku.com/v_show/id_XMTkwMTcyMjc2.html" class="list-group-item">处女星号游轮</a>
      <a href="http://v.youku.com/v_show/id_XMTkwMTczMzQ0.html" class="list-group-item">加勒比游轮</a>

      <a href="http://v.youku.com/v_show/id_XMTYwNDUyMTcy.html" class="list-group-item">意大利</a>
      <a href="http://v.youku.com/v_show/id_XMTYwNDQ0Mjg0.html" class="list-group-item">澳大利亚和新西兰</a>
      <a href="http://v.youku.com/v_show/id_XMTYwNDIxNTUy.html" class="list-group-item">南非</a>
      <a href="http://v.youku.com/v_show/id_XMTYwNDE1MDk2.html" class="list-group-item">肯尼亚</a>
      <a href="http://v.youku.com/v_show/id_XMTYwMzcyNzIw.html" class="list-group-item">埃及</a>
      <a href="http://v.youku.com/v_show/id_XMTkwMTc1MTc2.html" class="list-group-item">希腊</a>
      <a href="http://v.youku.com/v_show/id_XMTYwNDU0MTg4.html" class="list-group-item">西班牙和葡萄牙</a>
      <a href="http://v.youku.com/v_show/id_XMTYwNDM1ODgw.html" class="list-group-item">奥地利、德国、法国、瑞士、意大利、瑞士和梵蒂冈</a>
      <a href="http://v.youku.com/v_show/id_XMTYwNDE5OTg0.html" class="list-group-item">迪拜</a>
      <a href="http://v.youku.com/v_show/id_XMTkwMTY5NzA0.html" class="list-group-item">美国</a>
      <a href="http://v.youku.com/v_show/id_XMTYwNDUxOTU2.html" class="list-group-item">英国</a>
      <a href="http://v.youku.com/v_show/id_XMTYwNDU3MTg4.html" class="list-group-item">瑞士</a>
      <a href="http://v.youku.com/v_show/id_XMTYwNDUzOTQ0.html" class="list-group-item">突尼斯</a>
    </div>

    
  </div>
</div>