config/routes.rb
Utour::Application.routes.draw do

  resources :date_and_prices

  resources :tours do
    get 'legacy', on: :member
    get 'show_docx', on: :member
  end

  resources :bookings do
    get 'account_specific_index', on: :collection
  end

  resources :accounts do
    get 'activate_show', on: :member
    post 'activate', on: :member
  end

  resources :agents

  resources :images, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :visa_infos, only: [:show]

  root 'front30#home'

  match '/signup',  to: 'accounts#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signout', to: 'sessions#destroy', via: 'get'

  match '/legacy/home', to: 'legacies#home', via: 'get'

  match '/legacy/group_tours', to: 'legacies#group_tours', via: 'get'
  match '/legacy/free_tours', to: 'legacies#free_tours', via: 'get'
  match '/legacy/assorted', to: 'legacies#assorted', via: 'get'
  match '/legacy/visa', to: 'legacies#visa', via: 'get'
  match '/legacy/my_booking', to: 'legacies#my_booking', via: 'get'
  match '/legacy/booking_status', to: 'legacies#booking_status', via: 'get'
  match '/legacy/info', to: 'legacies#info', via: 'get'
  match '/legacy/guide', to: 'legacies#guide', via: 'get'

  match '/wechat', to: 'wechats#check', via: 'get'
  match '/wechat', to: 'wechats#message', via: 'post'
  match '/wechat/debug', to: 'wechats#debug', via: 'get'

  match '/tiger', to: 'wechat_webs#tiger', via: 'get'
  match '/lion', to: 'wechat_webs#lion', via: 'get'
  match '/tiger/group_travel', to: 'wechat_webs#group_travel', via: 'get'
  match '/lion/group_travel', to: 'wechat_webs#group_travel', via: 'get'
  match '/lion/visa', to: 'wechat_webs#visa', via: 'get'
  match '/lion/trade', to: 'wechat_webs#trade', via: 'get'
  match '/lion/video', to: 'wechat_webs#video', via: 'get'
  match '/lion/contact', to: 'wechat_webs#contact', via: 'get'
  match '/lion/feedback', to: 'wechat_webs#feedback', via: 'post'
  match '/lion/diy', to: 'wechat_webs#diy', via: 'get'
  match '/lion/sale', to: 'wechat_webs#sale', via: 'get'
  match '/lion/guide', to: 'wechat_webs#guide', via: 'get'
  get '/lion/visa_detail', to: 'wechat_webs#visa_detail'

  get '/landing_page', to: 'front30#landing_page'

  get '/front30/home', to: 'front30#home'
  get '/front30/contact_about', to: 'front30#contact_about'
  get '/front30/about', to: 'front30#about'
  get '/front30/dm', to: 'front30#dm'
  get '/front30/video', to: 'front30#video'
  get '/front30/travel_guide', to: 'front30#travel_guide'
  get '/front30/group', to: 'front30#group'
  get '/front30/free', to: 'front30#free'
  get '/front30/onsale', to: 'front30#onsale'
  get '/front30/quick_booking', to: 'front30#quick_booking'

  

  namespace :admin do |admin|
    
    resources :accounts
    resources :admins
    resources :operators
    resources :sales
    resources :agents

    resources :tours do
      resources :departures do 
        resources :prices
      end
    end
    resources :bookings
    resources :user_groups
    resources :date_and_prices
    resources :shelves

    resources :feature_tag_connections, only: [:new, :create, :destroy, :index]
    resources :feature_tags, only: [:new, :create, :destroy, :index]
    resources :invitation_codes, only: [:new, :create, :destroy, :index]
    resources :images, only: [:create, :destroy, :index]
    resources :sites
    resources :activities
    resources :days

    resources :visa_infos, only: [:new, :create, :destroy, :index]
    

    resources :invitation_codes do |invitation_code|
      get 'cancel', on: :member
    end
    
    resources :sessions, only: [:new, :create, :destroy]

    resources :sale_channels, only: [:create, :destroy, :update, :index]
    resources :sale_channel_maps, only: [:create, :destroy]

    get '/', to: 'plateforms#dashboard'
    get '/home', to: 'plateforms#home'
    get '/inbox', to: 'plateforms#inbox'
    get '/email_list', to: 'plateforms#email_list'
    get '/email_compose', to: 'plateforms#email_compose'
    get '/calendar', to: 'plateforms#calendar'
    get '/invitation_code_control', to: 'plateforms#invitation_code_control'
    get '/account_control', to: 'plateforms#account_control'

    get '/staff_index', to: 'plateforms#staff_index'
    get '/agent_index', to: 'plateforms#agent_index'
    get '/booking_index', to: 'plateforms#booking_index'
    get '/new_tour', to: 'plateforms#new_tour'
    get '/edit_tour', to: 'plateforms#edit_tour'
    get '/index_tour', to: 'plateforms#index_tour'

    get '/new_shelf', to: 'plateforms#new_shelf'
    get '/edit_shelf', to: 'plateforms#edit_shelf'
    get '/decorate_tour', to: 'plateforms#decorate_tour'
    get '/index_shelf', to: 'plateforms#index_shelf'

    get '/tag_control', to: 'plateforms#tag_control'
    get '/date_and_price_control', to: 'plateforms#date_and_price_control'
    get '/image_admin', to: 'plateforms#image_admin'
    get '/site_admin', to: 'plateforms#site_admin'
    get '/new_site_admin', to: 'plateforms#new_site_admin'

    get '/get_image_url', to: 'images#get_image_url'
    get '/get_image_list_by_site_id', to: 'sites#get_image_list_by_site_id'

    get '/departure_admin', to: 'plateforms#departure_admin'
    get '/price_admin', to: 'plateforms#price_admin'

    get '/sale_channels_admin', to: 'plateforms#sale_channels_admin'
    get '/agents_admin', to: 'plateforms#agents'
    get '/bookings_admin', to: 'plateforms#bookings_admin'
    get '/my_invitation_code', to: 'plateforms#my_invitation_code'

      match '/signup',  to: 'accounts#new', via: 'get'
      match '/signin',  to: 'sessions#new', via: 'get'
      match '/signout', to: 'sessions#destroy', via: 'delete'
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
	validates :name, :presence => { :message => "图片名称为必填" }, :length => { :in => 1..128, :message => "图片名称过长" }
 
	has_attached_file :photo, :styles => { :medium => "300x300>", :small => '100x100>', :thumb => '100x100#' }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  has_many :image_and_sites, :dependent => :destroy
  has_many :sites, through: :image_and_sites
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController
	skip_before_filter :verify_authenticity_token, :only => [:create]
	def index
	end

	def show
	end

	def create
		@image = Image.new(image_params)
		respond_to do |format|
			if @image.save
				format.json { render json: @image, status: :ok }
				format.html { redirect_to '/admin#admin/image_admin.html' } 
			else
				format.json { render json: @image.errors, status: :failed }
				format.html {
					@images = Image.all 
					#flash.now[:errors] =  @image.errors
					redirect_to "/admin#admin/image_admin.html", :flash => { :error => @image.errors.to_json }
				}
			end
		end
		
	end

	def destroy
		@image = Image.find_by_id(params[:id])
		@image.destroy
		redirect_to "/admin#admin/image_admin.html", :notice => "图片资源删除成功"
	end

	def get_image_url
		@image = Image.find_by_id(params[:id])
		if @image.present?
			if params[:type].present?
				render json: { :url => @image.photo.url(params[:type].intern)  }.to_json , status: :ok
			else
				render 
			end
		else
			render json: {:url => "/"}.to_json
		end
	end

	private
	def image_params
		params.require(:image).permit(:name, :description, :image_type, :photo)
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show
  	@image = Image.find params[:id]
  	render layout: "front30"
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/admin/images/_form.html.erb
<%#= form_for [:admin, image], :remote => true, :html => {:role => "form", :id => id, :multipart => true, :class => "smart-form", :'data-type' => 'json' } do |f| %>
<%= form_for [:admin, image], :html => {:role => "form", :id => id, :multipart => true, :class => "smart-form" } do |f| %>
<% if flash[:error].present? %>
<p><%= flash[:error] %></p>
<% end %>
<fieldset>

  
  <section>
    <div class="row">
      <%= f.label :image_type, '图片类别', :class => "label col col-2" %>
      <div class="col col-10">
        <label class="input"></i>
          <%= f.select :image_type, 
          "<option value='首页1x1'>首页1x1</option>
          <option value='首页2x1'>首页2x1</option>
          <option value='亚洲DM'>亚洲DM</option>
          <option value='欧洲DM'>欧洲DM</option>
          <option value='奥新DM'>奥新DM</option>
          <option value='非洲DM'>非洲DM</option>
          <option value='团队封面'>团队封面</option>
          <option value='团队图标'>团队图标</option>
          <option value='景点照片'>景点照片</option>".html_safe, {}, { class: "form-control" } %>
        </label>
      </div>
    </div>
  </section>

  <section>
    <div class="row">
      <%= f.label :name, '图片名称', :class => "label col col-2" %>
      <div class="col col-10">
        <label class="input"></i>
          <%= f.text_field :name, placeholder: "注意: 1. 名字切勿太长. 2. 不要空格和符号. 2. 将来可以凭此检索" %>
        </label>
      </div>
    </div>
  </section>

  <section>
    <div class="row">
      <%= f.label :description, '图片简介', :class => "label col col-2" %>
      <div class="col col-10">
        <label class="input">
          <%= f.text_field :description, placeholder: "介绍和备注以资参考" %>
        </label>
      </div>
    </div>
  </section>

</fieldset>

<fieldset>
  <section>
    <div class="row">
      <%= f.label :photo, '上传图片', :class => "label col col-2" %>
      <div class="col col-10">
        <label class="input">
          <%= f.file_field :photo %>
        </label>
      </div>
    </div>
  </section>

</fieldset>

<footer>
  <%= f.submit "提交", :class => "btn btn-primary" %>
</footer>
<% end %>

app/views/admin/images/_index.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th class="col-md-1">编号</th>
      <th class="col-md-1">类别</th>
      <th class="col-md-3">名称</th>
      <th class="col-md-3">简介</th>
      <th class="col-md-4">图片预览</th>
      <th class="col-md-1">操作</th>
    </tr>
  </thead>
  <tbody>
    <% images.each do |image| %>
    <tr>
      <td><%= image.id %></td>
      <td><%= image.image_type %></td>
      <td><%= trim_name(image.name, 30) %></td>
      <td><%= trim_name(image.description, 30) %></td>
      <td><%= image_tag image.photo.url(:thumb) %></td>
      <td>
        <%= link_to "删除", admin_image_path(image), method: :delete, class: "btn btn-primary" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/images/create.html.erb
<h1>Admin::Images#create</h1>
<p>Find me in app/views/admin/images/create.html.erb</p>

app/views/admin/images/destroy.html.erb
<h1>Admin::Images#destroy</h1>
<p>Find me in app/views/admin/images/destroy.html.erb</p>

app/views/admin/images/index.html.erb
<h1>Admin::Images#index</h1>
<p>Find me in app/views/admin/images/index.html.erb</p>